"""PostgreSQL connectivity owned by the engine."""

from engine.persistence.access_policy import (
    AccessChangeRejected,
    AccessPolicyControlUnavailable,
    PolicyEpoch,
    PostgreSQLAccessPolicyControl,
    ResourceAccessRevocation,
)
from engine.persistence.configuration import (
    LEARNING_ROLE,
    OPERATOR_ROLE,
    RELEASE_DEFINER_ROLE,
    DatabaseConfiguration,
    DatabaseConfigurationError,
    DatabasePurpose,
    HarnessDatabaseConfigurations,
    load_database_configuration,
    load_harness_database_configurations,
)
from engine.persistence.context_runs import (
    ContextRunOperatorAccessRequest,
    ContextRunOperatorAuthenticationRejected,
    ContextRunOperatorAuthenticator,
    ContextRunOperatorAuthority,
    ContextRunOperatorAuthorityUnavailable,
    ContextRunOperatorAuthorization,
    ContextRunReaderUnavailable,
    ContextRunView,
    OperatorAuthorizationProvenance,
    PostgreSQLContextRunReader,
    VerifiedContextRunOperatorIdentity,
)
from engine.persistence.control_sources import PostgreSQLControlStore
from engine.persistence.database import create_database_engine
from engine.persistence.membership_context import (
    MembershipAuthorityUnavailable,
    MembershipIdentity,
    MembershipNotCurrent,
    PostgreSQLMembershipAuthority,
)
from engine.persistence.releases import PostgreSQLReleaseStore
from engine.persistence.role_guard import (
    assert_control_role,
    assert_learning_role,
    assert_runtime_role,
    assert_security_operator_role,
    assert_worker_role,
)
from engine.persistence.tenant_context import (
    OrganizationContextBindingError,
    organization_transaction,
)
from engine.persistence.worker_jobs import (
    DEFAULT_WORKER_LEASE_TTL_SECONDS,
    MAX_WORKER_LEASE_TTL_SECONDS,
    PostgreSQLWorkerLeaseAuthority,
    PostgreSQLWorkerLeaseIssuer,
    WorkerExecutionIdentity,
    WorkerLeaseAuthorityUnavailable,
    WorkerLeaseIssueNotAvailable,
    WorkerLeaseIssueRequest,
    WorkerLeaseRedemption,
    WorkerNoOpAuditReceipt,
    WorkerNoOpCompletion,
    WorkerNoOpOutcome,
)

__all__ = [
    "DatabaseConfiguration",
    "AccessChangeRejected",
    "AccessPolicyControlUnavailable",
    "DatabaseConfigurationError",
    "DatabasePurpose",
    "HarnessDatabaseConfigurations",
    "LEARNING_ROLE",
    "OPERATOR_ROLE",
    "RELEASE_DEFINER_ROLE",
    "MembershipAuthorityUnavailable",
    "MembershipIdentity",
    "MembershipNotCurrent",
    "PolicyEpoch",
    "PostgreSQLAccessPolicyControl",
    "ContextRunOperatorAccessRequest",
    "ContextRunOperatorAuthenticationRejected",
    "ContextRunOperatorAuthenticator",
    "ContextRunOperatorAuthority",
    "ContextRunOperatorAuthorityUnavailable",
    "ContextRunOperatorAuthorization",
    "ContextRunReaderUnavailable",
    "ContextRunView",
    "OperatorAuthorizationProvenance",
    "PostgreSQLContextRunReader",
    "PostgreSQLControlStore",
    "VerifiedContextRunOperatorIdentity",
    "ResourceAccessRevocation",
    "OrganizationContextBindingError",
    "PostgreSQLMembershipAuthority",
    "PostgreSQLReleaseStore",
    "PostgreSQLWorkerLeaseAuthority",
    "PostgreSQLWorkerLeaseIssuer",
    "WorkerExecutionIdentity",
    "WorkerLeaseAuthorityUnavailable",
    "WorkerLeaseIssueNotAvailable",
    "WorkerLeaseIssueRequest",
    "WorkerLeaseRedemption",
    "WorkerNoOpAuditReceipt",
    "WorkerNoOpCompletion",
    "WorkerNoOpOutcome",
    "DEFAULT_WORKER_LEASE_TTL_SECONDS",
    "MAX_WORKER_LEASE_TTL_SECONDS",
    "assert_runtime_role",
    "assert_learning_role",
    "assert_security_operator_role",
    "assert_control_role",
    "assert_worker_role",
    "create_database_engine",
    "load_database_configuration",
    "load_harness_database_configurations",
    "organization_transaction",
]
